//
//  shree.m
//  PrimeMarathiNews
//
//  Created by Shree Bhagwat on 11/11/19.
//  Copyright © 2019 Shree Bhagwat. All rights reserved.
//

#import <Foundation/Foundation.h>
// Generated by Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import GoogleMobileAds;
@import ObjectiveC;
@import QuartzCore;
@import UIKit;
#endif
#import "VKSideMenu.h"
#import "/Users/shreebhagwat/Downloads/iOS News App - Swift Package/Source Code/iOS_NewsApp_SourceCode/LTL Source Code/NewsAppPro/NewsAppPro-Bridging-Header.h"

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="NewsAppPro",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UILabel;
@class UIButton;
@class UIScrollView;
@class UIView;
@class UIImageView;
@class UIWebView;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC10NewsAppPro7AboutUs")
@interface AboutUs : UIViewController <UIWebViewDelegate>
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblstatusbar;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheader;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheadername;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnback;
@property (nonatomic, strong) IBOutlet UIScrollView * _Nullable myScrollview;
@property (nonatomic, strong) IBOutlet UIView * _Nullable myView1;
@property (nonatomic, strong) IBOutlet UIView * _Nullable myView2;
@property (nonatomic, strong) IBOutlet UIView * _Nullable myView3;
@property (nonatomic, strong) IBOutlet UIView * _Nullable myView4;
@property (nonatomic, strong) IBOutlet UIView * _Nullable myView5;
@property (nonatomic, strong) IBOutlet UIView * _Nullable myView6;
@property (nonatomic, strong) IBOutlet UIView * _Nullable myView7;
@property (nonatomic, strong) IBOutlet UIImageView * _Nullable imglogo;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblappname;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblappversion;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblappwebsite;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblappemail;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblappmobno;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblcompany;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblappdesc;
@property (nonatomic, strong) IBOutlet UIWebView * _Nullable mywebview;
- (void)viewDidLoad;
- (void)webViewDidStartLoad:(UIWebView * _Nonnull)webView;
- (void)webView:(UIWebView * _Nonnull)webView didFailLoadWithError:(NSError * _Nonnull)error;
- (void)webViewDidFinishLoad:(UIWebView * _Nonnull)webView;
- (BOOL)webView:(UIWebView * _Nonnull)webView shouldStartLoadWithRequest:(NSURLRequest * _Nonnull)request navigationType:(UIWebViewNavigationType)navigationType SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLayoutSubviews;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnBackClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class UITextView;
@class UITableViewCell;
@class UITapGestureRecognizer;

SWIFT_CLASS("_TtC10NewsAppPro11AllComments")
@interface AllComments : UIViewController <UITableViewDataSource, UITableViewDelegate, UITextViewDelegate>
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblstatusbar;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheader;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheadername;
@property (nonatomic, strong) IBOutlet UITableView * _Nullable myTableView;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnComment;
@property (nonatomic, strong) IBOutlet UIView * _Nullable opacityView;
@property (nonatomic, strong) IBOutlet UIView * _Nullable commentView;
@property (nonatomic, strong) IBOutlet UIView * _Nullable imgCommentView;
@property (nonatomic, strong) IBOutlet UIImageView * _Nullable imgComment;
@property (nonatomic, strong) IBOutlet UITextView * _Nullable txtComment;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnSend;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (IBAction)OnCommentsClickWithSender:(UIButton * _Nonnull)sender;
- (void)keyboardWillShowWithNotification:(NSNotification * _Nonnull)notification;
- (void)keyboardWillHideWithNotification:(NSNotification * _Nonnull)notification;
- (void)handleSingleTap:(UITapGestureRecognizer * _Nullable)recognizer;
- (IBAction)OnSendCommentsClickWithSender:(UIButton * _Nonnull)sender;
- (void)viewDidLayoutSubviews;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnBackClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIWindow;
@class UIApplication;

SWIFT_CLASS("_TtC10NewsAppPro11AppDelegate")
@interface AppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow * _Nullable window;
- (BOOL)application:(UIApplication * _Nonnull)application didFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions SWIFT_WARN_UNUSED_RESULT;
- (void)application:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo fetchCompletionHandler:(void (^ _Nonnull)(UIBackgroundFetchResult))completionHandler;
- (void)applicationWillResignActive:(UIApplication * _Nonnull)application;
- (void)applicationDidEnterBackground:(UIApplication * _Nonnull)application;
- (void)applicationWillEnterForeground:(UIApplication * _Nonnull)application;
- (void)applicationDidBecomeActive:(UIApplication * _Nonnull)application;
- (void)applicationWillTerminate:(UIApplication * _Nonnull)application;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

/// CCheckbox is a custom UIButton class
/// which represents custom checkbox with
/// custom images
/// *
SWIFT_CLASS("_TtC10NewsAppPro9CCheckbox")
@interface CCheckbox : UIButton
@property (nonatomic, strong) UIImage * _Nullable normalImage;
@property (nonatomic, strong) UIImage * _Nullable selectedImage;
/// when set this variable checkbox status changed
@property (nonatomic) BOOL isCheckboxSelected;
- (void)layoutSubviews;
- (void)didTouchUpInside:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UISearchBar;
@class GADBannerView;
@class GADRequestError;
@class GADInterstitial;

SWIFT_CLASS("_TtC10NewsAppPro7CatList")
@interface CatList : UIViewController <GADBannerViewDelegate, GADInterstitialDelegate, UISearchBarDelegate, UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblstatusbar;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheader;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheadername;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnback;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnsearch;
@property (nonatomic, strong) IBOutlet UITableView * _Nullable myTableView;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblnodatafound;
@property (nonatomic, strong) IBOutlet UISearchBar * _Nullable searchBar;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnbacksearch;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayHeaderView:(UIView * _Nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (IBAction)OnSearchClickWithSender:(UIButton * _Nonnull)sender;
- (void)searchBarSearchButtonClicked:(UISearchBar * _Nonnull)searchBar;
- (IBAction)OnBackSearchClickWithSender:(UIButton * _Nonnull)sender;
- (void)viewDidLayoutSubviews;
- (void)adViewDidReceiveAd:(GADBannerView * _Nonnull)adView;
- (void)adView:(GADBannerView * _Nonnull)adView didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
- (void)interstitialDidReceiveAd:(GADInterstitial * _Nonnull)ad;
- (void)interstitialWillDismissScreen:(GADInterstitial * _Nonnull)ad;
- (void)interstitial:(GADInterstitial * _Nonnull)ad didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnBackClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;
@class UICollectionViewCell;
@class UICollectionViewLayout;

SWIFT_CLASS("_TtC10NewsAppPro10Categories")
@interface Categories : UIViewController <GADBannerViewDelegate, GADInterstitialDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UISearchBarDelegate>
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblstatusbar;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheader;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheadername;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnback;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnsearch;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblnodatafound;
@property (nonatomic, strong) IBOutlet UICollectionView * _Nullable myCollectionView;
@property (nonatomic, strong) IBOutlet UISearchBar * _Nullable searchBar;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnbacksearch;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (IBAction)OnSearchClickWithSender:(UIButton * _Nonnull)sender;
- (void)searchBar:(UISearchBar * _Nonnull)searchBar textDidChange:(NSString * _Nonnull)searchText;
- (void)searchBarSearchButtonClicked:(UISearchBar * _Nonnull)searchBar;
- (IBAction)OnBackSearchClickWithSender:(UIButton * _Nonnull)sender;
- (void)viewDidLayoutSubviews;
- (void)adViewDidReceiveAd:(GADBannerView * _Nonnull)adView;
- (void)adView:(GADBannerView * _Nonnull)adView didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnBackClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro12CategoryCell")
@interface CategoryCell : UICollectionViewCell
@property (nonatomic, strong) IBOutlet UIImageView * _Nullable catImageView;
@property (nonatomic, strong) IBOutlet UIImageView * _Nullable catOpacityImageView;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblCatName;
- (void)awakeFromNib;
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// CheckboxDelegate protocol to be confirmed
/// when you need callbacks for checkboc status change
/// *
SWIFT_PROTOCOL("_TtP10NewsAppPro16CheckboxDelegate_")
@protocol CheckboxDelegate
- (void)didSelect:(CCheckbox * _Nonnull)checkbox;
- (void)didDeselect:(CCheckbox * _Nonnull)checkbox;
@end


SWIFT_CLASS("_TtC10NewsAppPro6Colors")
@interface Colors : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro11CommentCell")
@interface CommentCell : UITableViewCell
@property (nonatomic, strong) IBOutlet UIView * _Nullable imgView;
@property (nonatomic, strong) IBOutlet UIImageView * _Nullable imgIcon;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblUserName;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblUserComment;
- (nullable instancetype)initWithCoder:(NSCoder * _Nullable)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (void)drawRect:(CGRect)rect;
- (CGSize)systemLayoutSizeFittingSize:(CGSize)targetSize withHorizontalFittingPriority:(UILayoutPriority)horizontalFittingPriority verticalFittingPriority:(UILayoutPriority)verticalFittingPriority SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC10NewsAppPro13CommonMessage")
@interface CommonMessage : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro11CommonUtils")
@interface CommonUtils : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro10DetailView")
@interface DetailView : UIViewController <GADBannerViewDelegate, GADInterstitialDelegate, UICollectionViewDataSource, UICollectionViewDelegate, UITableViewDataSource, UITableViewDelegate, UITextViewDelegate, UIWebViewDelegate>
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblstatusbar;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheader;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheadername;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnshare;
@property (nonatomic, strong) IBOutlet UIScrollView * _Nullable myScrollview;
@property (nonatomic, strong) IBOutlet UIView * _Nullable myView;
@property (nonatomic, strong) IBOutlet UIImageView * _Nullable iconImageView;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnIconImage;
@property (nonatomic, strong) IBOutlet UIView * _Nullable myView1;
@property (nonatomic, strong) IBOutlet UIView * _Nullable myView2;
@property (nonatomic, strong) IBOutlet UIView * _Nullable myView3;
@property (nonatomic, strong) IBOutlet UIView * _Nullable imgView;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblNewsTitle;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnPlay;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnFav;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblDate;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblViews;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnShare;
@property (nonatomic, strong) IBOutlet UIWebView * _Nullable webDesc;
@property (nonatomic, strong) IBOutlet UICollectionView * _Nullable myCollectionView;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblRelated;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblComments;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnViewAllComments;
@property (nonatomic, strong) IBOutlet UIImageView * _Nullable imgComments;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnComment;
@property (nonatomic, strong) IBOutlet UITableView * _Nullable myTableView;
@property (nonatomic, strong) IBOutlet UIView * _Nullable opacityView;
@property (nonatomic, strong) IBOutlet UIView * _Nullable commentView;
@property (nonatomic, strong) IBOutlet UIView * _Nullable imgCommentView;
@property (nonatomic, strong) IBOutlet UIImageView * _Nullable imgComment;
@property (nonatomic, strong) IBOutlet UITextView * _Nullable txtComment;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnSend;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnAllComments;
- (void)viewDidLoad;
- (void)webViewDidFinishLoad:(UIWebView * _Nonnull)webView;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (IBAction)OnShareClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnPlayClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnFavouriteClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnShareNewsClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnAllCommentsClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnCommentsViewAllClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnCommentsClickWithSender:(UIButton * _Nonnull)sender;
- (void)keyboardWillShowWithNotification:(NSNotification * _Nonnull)notification;
- (void)keyboardWillHideWithNotification:(NSNotification * _Nonnull)notification;
- (void)handleSingleTap:(UITapGestureRecognizer * _Nullable)recognizer;
- (IBAction)OnIconImageClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnSendCommentsClickWithSender:(UIButton * _Nonnull)sender;
- (void)viewDidLayoutSubviews;
- (void)adViewDidReceiveAd:(GADBannerView * _Nonnull)adView;
- (void)adView:(GADBannerView * _Nonnull)adView didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnBackClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro10Favourites")
@interface Favourites : UIViewController <GADBannerViewDelegate, GADInterstitialDelegate, UISearchBarDelegate, UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblstatusbar;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheader;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheadername;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnback;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnsearch;
@property (nonatomic, strong) IBOutlet UISearchBar * _Nullable searchBar;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnbacksearch;
@property (nonatomic, strong) IBOutlet UITableView * _Nullable myTableView;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblnodatafound;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayHeaderView:(UIView * _Nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (IBAction)OnSearchClickWithSender:(UIButton * _Nonnull)sender;
- (void)searchBarSearchButtonClicked:(UISearchBar * _Nonnull)searchBar;
- (IBAction)OnBackSearchClickWithSender:(UIButton * _Nonnull)sender;
- (void)viewDidLayoutSubviews;
- (void)adViewDidReceiveAd:(GADBannerView * _Nonnull)adView;
- (void)adView:(GADBannerView * _Nonnull)adView didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
- (void)interstitialDidReceiveAd:(GADInterstitial * _Nonnull)ad;
- (void)interstitialWillDismissScreen:(GADInterstitial * _Nonnull)ad;
- (void)interstitial:(GADInterstitial * _Nonnull)ad didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnBackClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextField;

SWIFT_CLASS("_TtC10NewsAppPro14ForgotPassword")
@interface ForgotPassword : UIViewController <UITextFieldDelegate>
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblstatusbar;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheader;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheadername;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnback;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblfgp;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lbldesc;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblemail;
@property (nonatomic, strong) IBOutlet UITextField * _Nullable txtemail;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnsend;
- (void)viewDidLoad;
- (IBAction)OnSendClickWithSender:(UIButton * _Nonnull)sender;
- (void)viewDidLayoutSubviews;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)receivePackageNameNotification:(NSNotification * _Nullable)notification;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnBackClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPageControl;
@class LCBannerView;
@class VKSideMenu;
@class VKSideMenuItem;

SWIFT_CLASS("_TtC10NewsAppPro18HomeViewController")
@interface HomeViewController : UIViewController <GADBannerViewDelegate, GADInterstitialDelegate, UICollectionViewDataSource, UICollectionViewDelegate, UISearchBarDelegate, UITableViewDataSource, UITableViewDelegate, LCBannerViewDelegate, VKSideMenuDataSource, VKSideMenuDelegate>
@property (nonatomic, strong) IBOutlet UIScrollView * _Nullable myScrollview;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblstatusbar;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheader;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheadername;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnleftmenu;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnsearch;
@property (nonatomic, strong) IBOutlet UIPageControl * _Nullable pagecontrol;
@property (nonatomic, weak) IBOutlet LCBannerView * _Null_unspecified baseBannerView;
@property (nonatomic, strong) IBOutlet UIView * _Nullable myView;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblCategories;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnCatViewAll;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblTop10News;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnTop10ViewAll;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblLatest;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnLatest;
@property (nonatomic, strong) IBOutlet UICollectionView * _Nullable myCollectionView;
@property (nonatomic, strong) IBOutlet UICollectionView * _Nullable myCollectionView2;
@property (nonatomic, strong) IBOutlet UITableView * _Nullable myTableView;
@property (nonatomic, strong) IBOutlet UISearchBar * _Nullable searchBar;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnbacksearch;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)bannerView:(LCBannerView * _Nullable)bannerView didScrollToIndex:(NSInteger)index;
- (void)bannerView:(LCBannerView * _Nullable)bannerView didClickedImageIndex:(NSInteger)index;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayHeaderView:(UIView * _Nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (IBAction)OnLeftMenuClickWithSender:(UIButton * _Nonnull)sender;
- (NSInteger)numberOfSectionsInSideMenu:(VKSideMenu * _Null_unspecified)sideMenu SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)sideMenu:(VKSideMenu * _Null_unspecified)sideMenu numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (VKSideMenuItem * _Null_unspecified)sideMenu:(VKSideMenu * _Null_unspecified)sideMenu itemForRowAtIndexPath:(NSIndexPath * _Null_unspecified)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)sideMenuDidShow:(VKSideMenu * _Nullable)sideMenu;
- (void)sideMenuDidHide:(VKSideMenu * _Nullable)sideMenu;
- (NSString * _Nullable)sideMenu:(VKSideMenu * _Nullable)sideMenu titleForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)sideMenu:(VKSideMenu * _Nullable)sideMenu didSelectRowAtIndexPath:(NSIndexPath * _Nullable)indexPath;
- (void)receiveFavouriteNotification:(NSNotification * _Nullable)notification;
- (void)receiveShareNotification:(NSNotification * _Nullable)notification;
- (IBAction)OnCatViewAllClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnTop10ViewAllClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnLatestViewAllClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnSearchClickWithSender:(UIButton * _Nonnull)sender;
- (void)searchBarSearchButtonClicked:(UISearchBar * _Nonnull)searchBar;
- (IBAction)OnBackSearchClickWithSender:(UIButton * _Nonnull)sender;
- (void)viewDidLayoutSubviews;
- (void)adViewDidReceiveAd:(GADBannerView * _Nonnull)adView;
- (void)adView:(GADBannerView * _Nonnull)adView didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
- (void)interstitialDidReceiveAd:(GADInterstitial * _Nonnull)ad;
- (void)interstitialWillDismissScreen:(GADInterstitial * _Nonnull)ad;
- (void)interstitial:(GADInterstitial * _Nonnull)ad didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
- (void)receivePackageNameNotification:(NSNotification * _Nullable)notification;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro7JYToast")
@interface JYToast : UILabel
@property (nonatomic, copy) NSString * _Nullable text;
- (void)awakeFromNib;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)drawTextInRect:(CGRect)rect;
- (void)didMoveToSuperview;
- (void)removeFromSuperview;
@end


SWIFT_CLASS("_TtC10NewsAppPro6Latest")
@interface Latest : UIViewController <GADBannerViewDelegate, GADInterstitialDelegate, UISearchBarDelegate, UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblstatusbar;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheader;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheadername;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnback;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnsearch;
@property (nonatomic, strong) IBOutlet UITableView * _Nullable myTableView;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblnodatafound;
@property (nonatomic, strong) IBOutlet UISearchBar * _Nullable searchBar;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnbacksearch;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayHeaderView:(UIView * _Nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (IBAction)OnSearchClickWithSender:(UIButton * _Nonnull)sender;
- (void)searchBarSearchButtonClicked:(UISearchBar * _Nonnull)searchBar;
- (IBAction)OnBackSearchClickWithSender:(UIButton * _Nonnull)sender;
- (void)viewDidLayoutSubviews;
- (void)adViewDidReceiveAd:(GADBannerView * _Nonnull)adView;
- (void)adView:(GADBannerView * _Nonnull)adView didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
- (void)interstitialDidReceiveAd:(GADInterstitial * _Nonnull)ad;
- (void)interstitialWillDismissScreen:(GADInterstitial * _Nonnull)ad;
- (void)interstitial:(GADInterstitial * _Nonnull)ad didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnBackClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro5Login")
@interface Login : UIViewController <CheckboxDelegate, UITextFieldDelegate>
@property (nonatomic, strong) IBOutlet UIScrollView * _Nullable myScrollview;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblwlctitle1;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblwlctitle2;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblemail;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblpassword;
@property (nonatomic, strong) IBOutlet UITextField * _Nullable txtemail;
@property (nonatomic, strong) IBOutlet UITextField * _Nullable txtpassword;
@property (nonatomic, weak) IBOutlet CCheckbox * _Null_unspecified checkbox;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblrememberme;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnlogin;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnskip;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnforgot;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lbldonotaccount;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnsignup;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblline;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnback;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (IBAction)OnLoginClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnSkipClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnForgotPasswordClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnSignUpClickWithSender:(UIButton * _Nonnull)sender;
- (void)viewDidLayoutSubviews;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)didDeselect:(CCheckbox * _Nonnull)checkbox;
- (void)didSelect:(CCheckbox * _Nonnull)checkbox;
- (void)receivePackageNameNotification:(NSNotification * _Nullable)notification;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnBackClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro5Modal")
@interface Modal : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC10NewsAppPro11NewsBigCell")
@interface NewsBigCell : UITableViewCell
@property (nonatomic, strong) IBOutlet UIView * _Nullable newsBackView;
@property (nonatomic, strong) IBOutlet UIView * _Nullable iconBackView;
@property (nonatomic, strong) IBOutlet UIImageView * _Nullable newsImageView;
@property (nonatomic, strong) IBOutlet UIImageView * _Nullable newsOpacityImageView;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblNewsTitle;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnPlay;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnFav;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblDate;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblViews;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnShare;
@property (nonatomic, strong) IBOutlet UIWebView * _Nullable webDesc;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro13NewsSmallCell")
@interface NewsSmallCell : UICollectionViewCell
@property (nonatomic, strong) IBOutlet UIView * _Nullable newsBackView;
@property (nonatomic, strong) IBOutlet UIView * _Nullable iconBackView;
@property (nonatomic, strong) IBOutlet UIImageView * _Nullable newsImageView;
@property (nonatomic, strong) IBOutlet UIImageView * _Nullable newsOpacityImageView;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblNewsTitle;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnPlay;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnFav;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblDate;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblViews;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnShare;
@property (nonatomic, strong) IBOutlet UIWebView * _Nullable webDesc;
- (void)awakeFromNib;
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro7Popular")
@interface Popular : UIViewController <GADBannerViewDelegate, GADInterstitialDelegate, UISearchBarDelegate, UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblstatusbar;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheader;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheadername;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnback;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnsearch;
@property (nonatomic, strong) IBOutlet UITableView * _Nullable myTableView;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblnodatafound;
@property (nonatomic, strong) IBOutlet UISearchBar * _Nullable searchBar;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnbacksearch;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayHeaderView:(UIView * _Nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (IBAction)OnSearchClickWithSender:(UIButton * _Nonnull)sender;
- (void)searchBarSearchButtonClicked:(UISearchBar * _Nonnull)searchBar;
- (IBAction)OnBackSearchClickWithSender:(UIButton * _Nonnull)sender;
- (void)viewDidLayoutSubviews;
- (void)adViewDidReceiveAd:(GADBannerView * _Nonnull)adView;
- (void)adView:(GADBannerView * _Nonnull)adView didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
- (void)interstitialDidReceiveAd:(GADInterstitial * _Nonnull)ad;
- (void)interstitialWillDismissScreen:(GADInterstitial * _Nonnull)ad;
- (void)interstitial:(GADInterstitial * _Nonnull)ad didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnBackClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro13PrivacyPolicy")
@interface PrivacyPolicy : UIViewController <UIWebViewDelegate>
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblstatusbar;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheader;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheadername;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnback;
@property (nonatomic, strong) IBOutlet UIView * _Nullable myView;
@property (nonatomic, strong) IBOutlet UIWebView * _Nullable myWebView;
- (void)viewDidLoad;
- (void)webViewDidStartLoad:(UIWebView * _Nonnull)webView;
- (void)webView:(UIWebView * _Nonnull)webView didFailLoadWithError:(NSError * _Nonnull)error;
- (void)webViewDidFinishLoad:(UIWebView * _Nonnull)webView;
- (BOOL)webView:(UIWebView * _Nonnull)webView shouldStartLoadWithRequest:(NSURLRequest * _Nonnull)request navigationType:(UIWebViewNavigationType)navigationType SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLayoutSubviews;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnBackClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro7Profile")
@interface Profile : UIViewController <UITextFieldDelegate>
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblstatusbar;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheader;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheadername;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnback;
@property (nonatomic, strong) IBOutlet UIScrollView * _Nullable myScrollview;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblsignup;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblusername;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblemail;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblpassword;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblcofirmpassword;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblphone;
@property (nonatomic, strong) IBOutlet UITextField * _Nullable txtusername;
@property (nonatomic, strong) IBOutlet UITextField * _Nullable txtemail;
@property (nonatomic, strong) IBOutlet UITextField * _Nullable txtpassword;
@property (nonatomic, strong) IBOutlet UITextField * _Nullable txtcofirmpassword;
@property (nonatomic, strong) IBOutlet UITextField * _Nullable txtphone;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnupdate;
- (void)viewDidLoad;
- (IBAction)OnUpdateProfileClickWithSender:(UIButton * _Nonnull)sender;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (IBAction)onKeyboardDoneClicked:(id _Nonnull)sender;
- (void)onKeyboardShow:(NSNotification * _Nullable)notification;
- (void)viewDidLayoutSubviews;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnBackClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro8Register")
@interface Register : UIViewController <UITextFieldDelegate>
@property (nonatomic, strong) IBOutlet UIScrollView * _Nullable myScrollview;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblsignup;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblusername;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblemail;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblpassword;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblcofirmpassword;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblphone;
@property (nonatomic, strong) IBOutlet UITextField * _Nullable txtusername;
@property (nonatomic, strong) IBOutlet UITextField * _Nullable txtemail;
@property (nonatomic, strong) IBOutlet UITextField * _Nullable txtpassword;
@property (nonatomic, strong) IBOutlet UITextField * _Nullable txtcofirmpassword;
@property (nonatomic, strong) IBOutlet UITextField * _Nullable txtphone;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnregister;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblalreadyaccount;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnlogin;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblline;
- (void)viewDidLoad;
- (IBAction)OnRegisterClickWithSender:(UIButton * _Nonnull)sender;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (IBAction)onKeyboardDoneClicked:(id _Nonnull)sender;
- (void)onKeyboardShow:(NSNotification * _Nullable)notification;
- (void)viewDidLayoutSubviews;
- (void)receivePackageNameNotification:(NSNotification * _Nullable)notification;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnLoginClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITouch;
@class UIEvent;
@class SCLButton;

SWIFT_CLASS("_TtC10NewsAppPro12SCLAlertView")
@interface SCLAlertView : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)buttonTapped:(SCLButton * _Nonnull)btn;
- (void)buttonTapDown:(SCLButton * _Nonnull)btn;
- (void)buttonRelease:(SCLButton * _Nonnull)btn;
- (void)keyboardWillShow:(NSNotification * _Nonnull)notification;
- (void)keyboardWillHide:(NSNotification * _Nonnull)notification;
- (void)tapped:(UITapGestureRecognizer * _Nonnull)gestureRecognizer;
- (void)updateShowTimeout;
- (void)hideView;
- (void)hideViewTimeout;
@end




SWIFT_CLASS("_TtC10NewsAppPro20SCLAlertViewStyleKit")
@interface SCLAlertViewStyleKit : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro9SCLButton")
@interface SCLButton : UIButton
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;

SWIFT_CLASS("_TtC10NewsAppPro23SWActivityIndicatorView")
@interface SWActivityIndicatorView : UIView
@property (nonatomic) CGFloat lineWidth;
@property (nonatomic) BOOL autoStartAnimating;
@property (nonatomic) BOOL hidesWhenStopped;
@property (nonatomic, strong) UIColor * _Nonnull color;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
@end


SWIFT_CLASS("_TtC10NewsAppPro10SearchView")
@interface SearchView : UIViewController <GADBannerViewDelegate, GADInterstitialDelegate, UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblstatusbar;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheader;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheadername;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnback;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnsearch;
@property (nonatomic, strong) IBOutlet UITableView * _Nullable myTableView;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblnodatafound;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)viewDidLayoutSubviews;
- (void)adViewDidReceiveAd:(GADBannerView * _Nonnull)adView;
- (void)adView:(GADBannerView * _Nonnull)adView didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
- (void)interstitialDidReceiveAd:(GADInterstitial * _Nonnull)ad;
- (void)interstitialWillDismissScreen:(GADInterstitial * _Nonnull)ad;
- (void)interstitial:(GADInterstitial * _Nonnull)ad didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnBackClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro6Sector")
@interface Sector : CAShapeLayer
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer SWIFT_UNAVAILABLE;
@end

@class UISwitch;

SWIFT_CLASS("_TtC10NewsAppPro7Setting")
@interface Setting : UIViewController
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblstatusbar;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheader;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheadername;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnback;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblenablepush;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnrateapp;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnmoreapp;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnprivacy;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnaboutus;
@property (nonatomic, strong) IBOutlet UISwitch * _Nullable privateSwitch;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (IBAction)OnSwitchValueChangedWithSender:(UISwitch * _Nonnull)sender;
- (IBAction)OnRateAppClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnMoreAppsClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnPrivacyPolicyClickWithSender:(UIButton * _Nonnull)sender;
- (IBAction)OnAboutUsClickWithSender:(UIButton * _Nonnull)sender;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnBackClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro8Settings")
@interface Settings : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro9Singleton")
@interface Singleton : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro7Spinner")
@interface Spinner : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10NewsAppPro13Top10ViewNews")
@interface Top10ViewNews : UIViewController <GADBannerViewDelegate, GADInterstitialDelegate, UISearchBarDelegate, UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblstatusbar;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheader;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblheadername;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnback;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnsearch;
@property (nonatomic, strong) IBOutlet UITableView * _Nullable myTableView;
@property (nonatomic, strong) IBOutlet UILabel * _Nullable lblnodatafound;
@property (nonatomic, strong) IBOutlet UISearchBar * _Nullable searchBar;
@property (nonatomic, strong) IBOutlet UIButton * _Nullable btnbacksearch;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayHeaderView:(UIView * _Nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (IBAction)OnSearchClickWithSender:(UIButton * _Nonnull)sender;
- (void)searchBarSearchButtonClicked:(UISearchBar * _Nonnull)searchBar;
- (IBAction)OnBackSearchClickWithSender:(UIButton * _Nonnull)sender;
- (void)viewDidLayoutSubviews;
- (void)adViewDidReceiveAd:(GADBannerView * _Nonnull)adView;
- (void)adView:(GADBannerView * _Nonnull)adView didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
- (void)interstitialDidReceiveAd:(GADInterstitial * _Nonnull)ad;
- (void)interstitialWillDismissScreen:(GADInterstitial * _Nonnull)ad;
- (void)interstitial:(GADInterstitial * _Nonnull)ad didFailToReceiveAdWithError:(GADRequestError * _Nonnull)error;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (IBAction)OnBackClickWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC10NewsAppPro19ZoomableImageSlider")
@interface ZoomableImageSlider : UIPageViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)closeButtonTapped;
- (nonnull instancetype)initWithTransitionStyle:(UIPageViewControllerTransitionStyle)style navigationOrientation:(UIPageViewControllerNavigationOrientation)navigationOrientation options:(NSDictionary<UIPageViewControllerOptionsKey, id> * _Nullable)options SWIFT_UNAVAILABLE;
@end


@interface ZoomableImageSlider (SWIFT_EXTENSION(NewsAppPro)) <UIPageViewControllerDataSource>
- (UIViewController * _Nullable)pageViewController:(UIPageViewController * _Nonnull)pageViewController viewControllerBeforeViewController:(UIViewController * _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)pageViewController:(UIPageViewController * _Nonnull)pageViewController viewControllerAfterViewController:(UIViewController * _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)presentationCountForPageViewController:(UIPageViewController * _Nonnull)pageViewController SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)presentationIndexForPageViewController:(UIPageViewController * _Nonnull)pageViewController SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@end

@class UIGestureRecognizer;

SWIFT_CLASS("_TtC10NewsAppPro25ZoomedPhotoViewController")
@interface ZoomedPhotoViewController : UIViewController <UIScrollViewDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)handleDoubleTapWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer;
- (void)swipeDownGestureAction;
- (UIView * _Nullable)viewForZoomingInScrollView:(UIScrollView * _Nonnull)scrollView SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
